apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
data:
  # property-like keys; each key maps to a simple value
  host: cluster0.xpkhnmq.mongodb.net
  database: library_db
  option: retryWrites=true&w=majority
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  # replace the secret values with yours
  username: ZGJ1c2VybmFtZQ==
  password: ZGJwYXNzd29yZA==
---
apiVersion: v1
kind: Service
metadata:
  name: book-api-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-book-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
      environment: dev
  template:
    metadata:
      labels:
        app: backend
        environment: dev
    spec:
      containers:
        - name: book-api
          image: spring-boot-k8s:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Never
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 1
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 1
          env: # array of environment variable definitions
            - name: MONGODB_URL
              valueFrom: # select individual keys in a ConfigMap
                configMapKeyRef:
                  name: mongodb-config
                  key: host
            - name: MONGODB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mongodb-config
                  key: database
            - name: MONGODB_OPTS
              valueFrom:
                configMapKeyRef:
                  name: mongodb-config
                  key: option
            - name: MONGODB_LOGIN
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: username
            - name: MONGODB_PWD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: password