apiVersion: v1
kind: Pod
metadata:
  name: guaranteed-pod
  namespace: rs-demo
spec:
  containers:
  - name: guaranteed-container-demo
    image: nginx
    resources:
      limits:
        memory: "200Mi"
        cpu: "700m"
      requests:
        memory: "200Mi"
        cpu: "700m"
