apiVersion: v1
kind: Pod
metadata:
  name: limit-request-example
  namespace: rs-demo
spec:
  containers:
  - name: nginx-demo
    image: nginx
    resources:
      requests:
        cpu: "500m"
        memory: "128Mi"        
      limits:
        cpu: "1"
        memory: "256Mi"
