apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
type: Opaque
data:
  {{- range $name, $config := .Values.secrets.values }}
  {{ $name }}: {{ $config | b64enc | quote  }}
  {{- end }}
